version: '3.4'

services:
  nginx:
    build: ./nginx
    image: app_nginx
    container_name: 'app_nginx'
    ports:
    - "80:80"

  testwebapp:
    image: ${DOCKER_REGISTRY-}testwebapp
    build:
      context: .
      dockerfile: ./TESTWebApp/Dockerfile
    ports:
    - 5000:5000
